steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/curso-r/exemplodeploy', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/curso-r/exemplodeploy']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'exemplodeploy', '--image', 'gcr.io/curso-r/exemplodeploy', '--region', 'us-central1','--platform', 'managed', '--quiet', '--memory', '512Mi']
images:
- gcr.io/curso-r/exemplodeploy